<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE Music_library [
<!ELEMENT Music_library (title,artist,country,price,year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ENTITY MS "thatz life">
]>
<Music_library>
    <title>YLO</title>
    <artist>&MS; -Jenny Dan</artist>
    <country>Germanyo</country>
    <price>$12</price>
    <year>2002</year>
</Music_library>